<h2>Game need information </h2>


<b>Cocos2dx<b>

Install:

1) install cocos2dx C++ <a href="http://www.cocos2d-x.org/docs/cocos2d-x/en/installation/Linux.html"> read more </a> 



<b>Convert .Excel File to .JSON </b>

2) npm install convert-excel-to-json  OR  npm install -g convert-excel-to-json   
	if you want to learn more then <a href="https://www.npmjs.com/package/convert-excel-to-json " > read here:</a> 

Process:
	
	make script for it and run on terminal. 
steps: 
	make .sh file
	give permission for execute 
	run on terminal ./filename.sh


<b>Android studio</b>

3) To run in android need tools
	a) Android SDK Linux
	b) Android NDK r16b
	c) ANT



